### ISSUE TITLE
Cannot enable plugin after pip install

### ISSUE THREAD

**Issue by harel** [overhangio/tutor-gradebook#1]
Following the setup steps, I can pip install tutor-gradebook from github. 
However, after the setup I cannot enable the plugin: 

```
$ tutor plugins enable gradebook
Error: plugin 'gradebook' is not installed.
```

I've tried to pip install within a running tutor container (lms and cms), or pip installing as sudo vs regular user. Nothing seems to work. 

Any ideas what is wrong? 

Many thanks!

**Comment by regisb** [comment]
Hi! This plugin is deprecated. In tutor v12 you should now install the Gradebook from the MFE plugin: https://github.com/overhangio/tutor-mfe

For further information and support, please go to the Tutor community forums: https://discuss.overhang.io/
